name: putra_jaya_billiard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0" # Memperluas rentang kompatibilitas Dart

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  cloud_functions: 6.0.0
  file_picker: ^6.2.0
  flutter_libserialport: ^0.5.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  sliding_up_panel: ^2.0.0+1
  pdf: ^3.10.8
  printing: ^5.12.0
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

  # --- TAMBAHKAN INI ---
  hive: ^2.2.3         # Untuk database Hive
  hive_flutter: ^1.1.0 # Untuk integrasi dengan Flutter
  path_provider: ^2.0.11 # Untuk mendapatkan path penyimpanan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # --- TAMBAHKAN INI ---
  hive_generator: ^2.0.0 # Untuk generate adapter Hive
  build_runner: ^2.3.3   # Untuk menjalankan generator

flutter:
  uses-material-design: true
