name: putra_jaya_billiard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0" # Memperluas rentang kompatibilitas Dart

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  cloud_functions: 6.0.0

  flutter_libserialport: ^0.5.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  sliding_up_panel: ^2.0.0+1
  pdf: ^3.10.8
  printing: ^5.12.0
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
